# Generated by Django 3.0.5 on 2020-04-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='recipes',
            field=models.ManyToManyField(to='main_app.Recipe'),
        ),
    ]
